#!/bin/bash

# 'use strict';
set -eou pipefail

# Refuse to act if there's a diff.
if git ls-files -d -m | grep -q . ; then
   exit 1
fi

echo 'No files seem changed; continuing.'

# Switch to master at the start & end, for sanity.
git fetch origin
git checkout master
git rebase origin/master || git rebase --abort

TO_REMOVE=""
for branch in $(git branch --merged | grep -v master )
do
    # If the branch has no remote tracking branch, and it is already merged
    # origin/master, then throw it away.
    if ! git config --get branch.$branch.merge >/dev/null; then
        TO_REMOVE="$TO_REMOVE $branch"
    fi
done

git checkout master
for branch in $TO_REMOVE ; do
    git branch -d "$branch"
done
