#!/usr/bin/zsh
for in in $(seq 3) ; do
pidof chromium >/dev/null && { killall chromium ; sleep 1 }
done
gsettings set org.gnome.desktop.interface scaling-factor 1
chromium --force-device-scale-factor=1 & disown

